# Generated by Django 5.0.3 on 2024-04-13 11:07

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('done', models.BooleanField(default=False)),
                ('result', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SupportTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=100)),
                ('issue', models.TextField()),
                ('status', models.CharField(choices=[('Open', 'OPEN'), ('In Progress', 'IN_PROGRESS'), ('Closed', 'CLOSED')], max_length=20)),
            ],
        ),
    ]
